export const RSS_FEEDS = [
  // ================= INDIA FEEDS (50%) =================
  {
    id: "et-markets",
    name: "Economic Times Markets",
    url: "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
    category: "Indian Stocks",
    region: "India",
  },
  {
    id: "et-stocks",
    name: "Economic Times Stocks",
    url: "https://economictimes.indiatimes.com/markets/stocks/rssfeeds/2146842.cms",
    category: "Indian Stocks",
    region: "India",
  },
  {
    id: "et-ipo",
    name: "Economic Times IPO",
    url: "https://economictimes.indiatimes.com/markets/ipos/fpos/rssfeeds/32997685.cms",
    category: "Indian IPO",
    region: "India",
  },
  {
    id: "livemint-markets",
    name: "Livemint Markets",
    url: "https://www.livemint.com/rss/markets",
    category: "Indian Markets",
    region: "India",
  },
  {
    id: "livemint-companies",
    name: "Livemint Companies",
    url: "https://www.livemint.com/rss/companies",
    category: "Indian Corporate",
    region: "India",
  },
  {
    id: "business-standard-markets",
    name: "Business Standard Markets",
    url: "https://www.business-standard.com/rss/markets-106.rss",
    category: "Indian Markets",
    region: "India",
  },
  {
    id: "business-standard-company",
    name: "Business Standard Companies",
    url: "https://www.business-standard.com/rss/companies-101.rss",
    category: "Indian Corporate",
    region: "India",
  },
  {
    id: "sebi",
    name: "SEBI Announcements",
    url: "https://www.sebi.gov.in/sebirss.xml",
    category: "Regulation",
    region: "India",
  },
  {
    id: "rbi-press",
    name: "RBI Press Releases",
    url: "https://www.rbi.org.in/pressreleases_rss.xml",
    category: "Policy",
    region: "India",
  },
  {
    id: "rbi-notifications",
    name: "RBI Notifications",
    url: "https://www.rbi.org.in/notifications_rss.xml",
    category: "Policy",
    region: "India",
  },
  {
    id: "gnews-india-market",
    name: "Google News India Market",
    url: "https://news.google.com/rss/search?q=Indian+stock+market+NSE+OR+BSE&hl=en-IN&gl=IN&ceid=IN:en",
    category: "Indian News",
    region: "India",
  },
  {
    id: "bse-india",
    name: "BSE India News",
    url: "https://news.google.com/rss/search?q=BSE+India+Announcements&hl=en-IN&gl=IN&ceid=IN:en",
    category: "Indian Corporate",
    region: "India",
  },

  // ================= WORLD FEEDS (50%) =================
  {
    id: "wsj-markets",
    name: "WSJ Markets",
    url: "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
    category: "World Markets",
    region: "Global",
  },
  {
    id: "wsj-business",
    name: "WSJ Business",
    url: "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml",
    category: "World Business",
    region: "Global",
  },
  {
    id: "cnbc-top",
    name: "CNBC Top News",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?profile=120000000&id=100003114",
    category: "World News",
    region: "Global",
  },
  {
    id: "cnbc-finance",
    name: "CNBC Finance",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?profile=120000000&id=10000664",
    category: "World Finance",
    region: "Global",
  },
  {
    id: "cnbc-investing",
    name: "CNBC Investing",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?profile=120000000&id=10000664",
    category: "World Investing",
    region: "Global",
  },
  {
    id: "yahoo-finance-us",
    name: "Yahoo Finance US",
    url: "https://finance.yahoo.com/news/rssindex",
    category: "World Finance",
    region: "Global",
  },
  {
    id: "ft-markets",
    name: "Financial Times Markets",
    url: "https://www.ft.com/myft/following/cfffa7ca-76db-4e7d-bd8e-cbceb8a2e5ca.rss",
    category: "World Markets",
    region: "Global",
  },
  {
    id: "ft-global-economy",
    name: "Financial Times Economy",
    url: "https://www.ft.com/global-economy?format=rss",
    category: "World Economy",
    region: "Global",
  },
  {
    id: "investopedia",
    name: "Investopedia",
    url: "https://www.investopedia.com/feedbuilder/feed/getfeed?feedName=article_daily",
    category: "Education & Insights",
    region: "Global",
  },
  {
    id: "reuters-business",
    name: "Reuters Business",
    url: "https://news.google.com/rss/search?q=Reuters+Business+News&hl=en-US&gl=US&ceid=US:en",
    category: "World Business",
    region: "Global",
  },
  {
    id: "bloomberg-markets",
    name: "Bloomberg Markets Search",
    url: "https://news.google.com/rss/search?q=Bloomberg+Markets&hl=en-US&gl=US&ceid=US:en",
    category: "World Markets",
    region: "Global",
  },
  {
    id: "crypto-cointelegraph",
    name: "Cointelegraph Crypto",
    url: "https://cointelegraph.com/rss",
    category: "Crypto",
    region: "Global",
  },
];

export const VIDEO_STREAMS = [
  // India Streams
  { id: "mc", name: "Moneycontrol Live", type: "channel", value: "UChftTVI0QJmyXkajQYt2tiQ", region: "India" },
  { id: "cnbc18", name: "CNBC TV18 Live", type: "channel", value: "UCmRbHAgG2k2vDUvb3xsEunQ", region: "India" },
  { id: "etnow", name: "ET Now Live", type: "channel", value: "UCI_mwTKUhicNzFrhm33MzBQ", region: "India" },
  { id: "zeebiz", name: "Zee Business Live", type: "channel", value: "UCkXopQ3ubd-rnXnStZqCl2w", region: "India" },
  // World Streams
  { id: "cnbc-world", name: "CNBC Live", type: "channel", value: "UCvJJ_dzjViJCoLf5uKUTcgA", region: "Global" },
  { id: "bloomberg-live", name: "Bloomberg Live", type: "channel", value: "UCIALMKvObZNtJ6AmdTo4yWU", region: "Global" },
  { id: "yahoo-finance-live", name: "Yahoo Finance Live", type: "channel", value: "UCEAZeUIeJs0IjQiqTCdXTuQ", region: "Global" }
];
